# Auschwitz {#auschwitz}

My memories have survived for seventeen years. Perhaps it will not be an accurate description. After so many years some events have been worn off already in my memory - others, though, are still fresh. I will try to present them as accurately as possible, as they have seen and experienced - first as a prisoner of the Nazi concentration camps in 1942-1944, then as a fugitive from the camp, hiding until the end of the war. 

I did not write those memories so far as the vision of the camp have always been before my eyes. Also, I experienced everything again in my dreams. I tried to forget. As a result, I did not get mad. Currently, all these events are just a distant memory. And if he did not notice the advertisement in "Voice of a Teacher", I would not have described them at all.

Twelfth of March 1943, after a year's stay in [Auschwitz](https://en.wikipedia.org/wiki/Auschwitz_concentration_camp), I was enlisted for transport to the concentration camp at [Neuengamme](https://en.wikipedia.org/wiki/Neuengamme_concentration_camp). The Lagerführer (camp-leader) from that camp came for us: [Lucie Mayer](http://www.theparasitologist.com/wp-content/uploads/2016/11/Albert-Lütkemeyer.pdf) (_Albert Lütkemeyer_). He chose a few musicians and one-thousand healthiest prisoners, among whom I found myself. A similar group was sent to [Buchenwald](https://en.wikipedia.org/wiki/Buchenwald_concentration_camp). March 13, after a thorough review, we already were on the way. By what cities we were driving - I can not say; we were transported on wired freight wagons. We sat on the floor in rows of five, and in the middle of the wagon were two armed SS men who guarded us. Escape was out of the question. We drove to the unknown - perhaps for better, perhaps for worse, who knows. For me, personally, a stone fell from my heart. I left a human slaughterhouse, from which it was a great fortune to get out alive. Many people there were killed. Counting them is impossible. I do not know if anyone would be able to read the names of the tortured. I doubt whether history will unearth the data.

