# Braunschweig {#braunschweig}

So our commando got the attention of the Sturmführer and the next transport has been designated to go to 'Dritte'. They herded us to the bathhouse, where a medical examination was scheduled. I got out accidentally by being in the dispensary and avoided transportation. Also, most of my friends managed to escape from the bathhouse.

For the next transport we got called up again. I knew that I won’t be able to avoid the transport every time. 

Therefor, I looked for a transport myself. That opportunity arose. A small commando were departing to [Braunschweig](https://www.braunschweig.de/english/culture/museum/memorial_centre_schillstrasse.html). To complete the group, they needed a bricklayer. I thought to myself that I can be as well a bricklayer. After all, these big blocks in the camp were also not build by experts. So I volunteered as a mason at Kapo Martin. Also I covered for Bolek Maciaszek and we got accepted and included for the drive out.

I left the camp in Neuengamme on May 3, year 1944. I did not assumed to go back there ever again. Fortunately. Because before the end of the war, the camp was liquidated: the prisoners were taken to ships which then got bombed. Only a handful were saved.

So to the camp at Braunschweig I came. There were Spaniards and French. A prison car took us to work. In the middle of the town we built a barrack. During our stay the town was bombed very often. People got buried under rubble. Even bunkers proved little protection against the bombs.

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(leaflet)

m <- leaflet() %>% setView(lng=10.5594, lat=52.2443, zoom=8) %>%
  addTiles() %>% # Add default OpenStreetMap map tiles
  addMarkers(lng=10.233499066, lat=53.4249983, popup="Braunschweig concentration camp")
m  # Print the map
```

<br>
<br>
We were not afraid to die from bombs. Each bombing elicited great joy from us. For us, what was bombing compared to be killed by the wheelbarrow, get a boot on the neck and suffocate or to drown in the muddy trench, or, at best, be shot like a dog.

Construction proceeded quickly and efficiently and soon I finished the construction. After a few days we were placed at a small village near Helmstedt. Here we fix the warehouses of the SS that were crumbling from the bombing.

Me as ‘bricklayer’, was told to fix the chimney. At first I thought that this wouldn’t be a too difficult job. I was wrong. I pretended to be an expert, but could not use a trowel. Soon I had to go through the exam. I got exposed. I was not sent to the camp, what I feared most. Instead, I was changed in function: I became an assistant in construction, and masons were brought from the village. They were two old Germany civilians. Together with Molik,we brought the bricks, stirring the lime and carried "miszung" up. The job was not the worst; it was far from the camp were we were constantly being routed up "Los ... los ..." Sometimes only Kapo Martin hunted us, but when we "bought" him some products from parcels, he calmed down. 

The repairs continued over time . No one was in no hurry. Neither the Kommandoführer was in a hurry to leave this secluded place away from the bombing, nor the SS, nor the gendarmes assigned for protection. After a few days the Kornmandoführer got acquainted with the owner of the buildings, a young German women. He began an affair with her, and we, in the best of our ability, we tried with our work to extend their romance.

In the afternoons and on Sundays we were taken to harvest. We put sheaves in the field. Occasionally, we were allowed to bathe in the stream. We could not complain. Bolek received parcels, which he shared with everyone. Next to us lived French prisoners of war. There were fifteen of them. Every morning, they went to work dressed in their military uniform. They returned late in the afternoon or evening. Often we envied their "freedom".

After renovating the floors and repairing the roof, we went down to the basement. Because of the raids, it was decided to put the bulk storage as low as possible. We started digging at in the rocky bottom where the crane would be stored. It was like working in the mine under electric light. We could not dig too deep, because of constant flooding from groundwater, which we had to remove by using a hand pump. We worked in shifts, day and night. The only entertainment at pouring water all-night, was listening to the radio brought by an SS man. This was the period of the Warsaw Uprising. Every day the fighting in Warsaw, every day of the massacre carried out in the heart of Polish. It stirred in us a passion for revenge. Our hearts breaking for our fighting countryman. Our hands tightened to fist ready to kill the animals personified in the SS. There were moments that I had to withstand the urge to kill an SS with his own weapon. I deliberated, however, and waited for a better opportunity.

I became restless, taciturn and only looking for sedation at work. Sunday came. It was the end of September 1944. Three of us gathered: Bolek Maciaszek, Molik and me. We started a long discussion. The main topic of our discussion was, escape, as soon as possible. Certainly the Warsaw Uprising will trigger reprisals against the Poles. For sure we will be driven to the camp. Faith already known. One way or the other, it ends in death. Molik was of the opinion that we needed to arrange civilian clothes. Apparently, he already made efforts with the French soldiers. Stubbornly he stuck to that plan. But that would only bring us in trouble, because it is difficult to trust people you do not know. How would it be organised? We did not know the French who would provide us the clothes. Our lives would be hanging on a hair. We could not find a solution, the more that Molik was not fully determined. We decided to flee, together with Bolek. The deadline was not agreed. We only waited for an opportunity. And an opportunity came... 
