# The Birthday {#birthday}

On 7 October 1944, our Kommandoführer celebrated his birthday. It was a Saturday. From early morning people congratulated him. There was no share from our part in it. For this occasion, Bolek devoted all cookies from the packages from his fiancee.

In the afternoon, our guards went to the owner of the buildings, a young German woman, for 'a treat'. Her husband was in the army, so she consoled herself when she could, with our Kommandoführer.

In the evening the whole company, already ‘tipsy', went in the direction of the village, leaving only two guards, also being tipsy, to guard the prisoners. One guard was checking the building going around from the top and the other went by the lower side. We were still not locked up in the cell - apparently because of the birthday celebration. So we were able to walk around the ground floor of the warehouse. The Prisoner from Netherlands, 'Pibel' (nicknamed because of his small posture) they made sandals. Others wrote letters. Kap Martin went out to the backyard to a German woman he fancied. 

A crazy opportunity. We went on the ramp. The guard walked and growled something to himself. Probably he wanted to go to sleep, and there he had to guard. Without wasting time I winked to Bolek. From the ramp he jumped on Fritz' his head and with one blow he felled him. We shoved him under the ramp and stripped him to the shirt. Bolek quickly put his uniform on and took the gun. We moved towards the second guard. He did not stop us as he thought that his colleague was approaching. We managed to overpower also this guard with one blow. Now we were the new the owners of the uniforms. The rifle we did not take, only the handgun, which later provided us many big favours.

As quick as lighting we jumped into the fields and meadows, in the direction of the forest, away from the warehouse. The first moment in freedom was crazy. After a short time it turned out that we lacked strength. Somehow we jumped over a ditch and stopped for a moment. We saw a herd of grazing cows. It looked like an army ready for a raid. It is hard to imagine how frightened we were. Already we thought it was a manhunt for us. Luckily it was only an illusion. Bolek and I kissed each other for good fortune to our journey... to Poland.

What happened in the camp after we fled, was described to me by mate Molik after the war. The germans alerted all the nearby villages. They occupied the buildings that we renovated. For defence they called the local Landwache. They put around machine guns and they waited. They thought we would come back with reinforcement, to rescue the other prisoners.

Escaping was easily. But what next? From one we knew, back to the camp is impossible. Either we reach homeland or we die. In no case we should fall into their claws alive. It would for sure mean death in wildest agony….
