# The Run {#run}

We decided to go for it. In the beginning we went off-roads. Crossing fields and through the forests. We avoided villages and people. In the morning we arrived at stacks of grain in the clearing. Further march was impossible. We hid in a pile of straw. A little sleep, meditating on our fate. Hunger began to tease us. We strengthen ourselves on raw carrot and cabbage and waited for the night. We could not go by roads. Our compass were the stars. We had bad luck, because for the whole three-week trip the weather was bad. Rain or cloudy nights did not allow us to get a good sense of direction. After three days of walking we decided to figure out where exactly we were going. We went to a village to read signposts for direction and place names. We had assumed that these three nights we walked for 100 km. It turned out that we are only 20 km from the place of escape and were walking back in the direction of the camp.

On the edge of the forest we entered the fenced area, were we could not get out. A large German shepherd ran to us, sniffed and walked away. He saw a German uniform, but did not sense who it got in it. There was a flash light. We saw the mast, and the Nazi flag. Nearby stood a police station. Despite the lack of strength with incredible speed we were outside the fence - to get as far as possible.

Sometimes we lied through the whole day in haystacks. In the fields we saw farmers plowing. Soggy patches, mud and rains forced us to take risks. We decided to march along roads, on which cars were moving. The direction of our march led to Berlin. Food we gained in different ways.

In different ways we struggled through Germany. Only a novelist could describe our journey, strewn with thousands of surprises.

One evening we reached some village. In one of the houses the light was on. We approached, of course, weapons in hand. A large family was speaking Ukrainian. We called the host. We told him to bring a loaf of bread and 5 Mark. He brought it. We gave him a pack of cigarettes. Both sides were happy.

Mostly we walked between the hours of 20 pm to 4 am, because then the Landwache descended from their posts. We got a long way. We reached Halle. Bypassing the city from the North, we encountered some dugout. We went to one of them and to our surprise we noticed the gun in the stands and the bunks full of soldiers, both sides completely full. One soldier apparently doing night duty gave salute and wanted to report something. We asked only for the way, of course in a opposite direction, and we left. I think they were an outposts anti-aircraft artillery.

On the second day, after traveling about 30 km, we lie under a haystack. Suddenly we hear the barking of dogs. Straight at us group goes hunting. Germans in hunting attire with dogs. They came to the railroad tracks. Apparently they did not want to go over the tracks, they turned into the drive. Meanwhile, we slipped out of the entanglement. Only the people who working on the field digging potatoes and beet, started to insult us and called out: “Deserters!”. It was in the evening. Quickly we went through the fields and entered in a meadow, where, in the bushes next to a brook, we waited for the night.
We came to the conclusion that this way we won’t get far. More and more surprises on the way. You can fall in one without even knowing when. We decided to try to ride the train. We had 5 marks and this encouraged us. The railway line Halle-Berlin is connected to the narrow-gauge railway line, encircling Berlin from the South. It was almost to the eastern border of Berlin. We decided to take this route and get outside Berlin, where the former Polish-German border seemed close to us. We arrived at the small railway station on the Elbe. We purchased tickets to the next station to the other side of the river. We expected that these 5 marks for this purpose would be used up. It turned out that tickets were much cheaper. We still have 2 mark, for which we bought a beer, and the rest for bread rolls. After an hour, the train came. We set off in the direction of Berlin. On the train was mandatory blackout. It was very beneficial for us. There wasn’t any control on the train. We drove to our station for which we bought the tickets. Had to get off, but inside the train, so warm, pleasant. We stayed sitting and made the kilometres while outside the wind and rain whistled. We did not get off.
The closer we got to Berlin, the more travellers got on the train. Mostly military. An officer asked me about something. I pretended to be asleep. He did not ask me anything more. We eventually got to Potsdam. Almost everyone got out. We also headed to the station, but the view controllers and the military startled us on time. Discreetly we retreated to the other side of the train. Rails, jump over the fence and we ended up on the street. It was about 23 hours. We wanted to get out of town, but in no way could not find the right way. We went astray for about four hours. In the end, we rested in a park with tall trees. A light rain fell.
At dawn, we looked at each other with pity. We looked like two paupers. Enough for anyone seeing us, at once to be recognised as fugitives.
We moved on further exploring a way out of the city. The city began getting more traffic. Right at the checkpoint we saw gendarmes. We sat on a bench and thought about what to do next. Two gendarmes clearly glared at us, but did not hooked on. Skulls on our caps and collars deterred everyone.
