# The Lift {#lift}

After some rest, we went out to the edge of town. It was already around eight o'clock. Two more hours of walking and we found ourselves in front of a yellow sign reading "Berlin-West." A few light beams of the sun came through. In the bushes we dried our clothes. We shaved, and with a piece of our ragged prisoner clothes we had under the SS uniforms, we cleaned our shoes and improving our looks somewhat, we moved over South of Berlin to the east. On the way we saw many destructions and ruins. A military unit marched through the street. The commander gave us the honour, which of course we responded to, and without the slightest hassle we went further.

On the way we passed some factories, fenced with wires. Some of them - newly built. In front of one of the factories we noticed 'stamped' people walking around unrestrained. The first of a kind we met with a "P" and the "U" sign. We assumed that "P" is a Pole. We went up to one man with the stamp "P". I first asked in German what this stamp means. He replied. Then in Polish I asked where he came from and what he was doing here. He replied that he was from Lódz. He was taken to work. To work in a factory. I told him who we were and we ask for help. He gave us 10 mark and showed us the way to the tram. Today, I wish I could thank him again , because neither his name nor his place of residence is known to me.

From the bridge over the river Spree, we took the tram to Berlin-East station. On the way, however, we changed plans. We were afraid of check-ups at the station by the military police. We went further, to the main highway in the direction of Frankfurt and Kostrzyn. We got off there. We wanted to take the road to reach some small station where there would be no checks for on getting on and buying a ticket.

The map we had ended after Berlin. The road we set off did not lead to the train station. Guided by our senses, we headed east. The entire route was filled with driving cars, which forced us to go of the road. We entered a military area and moved along the line, leaving Berlin behind us. On the way we picked potatoes from the mounds. We fried them in the woods. Back on strengths, we went on the main road. We stopped a truck. Two workers and a chauffeur were sitting in it. We asked them to take us to Kostrin because we were in a hurry. We needed to present ourselves for the army. We were going to the battlefront. They were surprised. They talked to each other until they finally demanded documents.

As our only document, we showed the gun. I sat down with the chauffeur and Bolek with the workers, and ordered them to move. They drove without a word. I do not know whether they were afraid or whether they were foreigners, because we encountered marching troops on the way, we were passing a town and the car did not stop for a moment. 