# The Bridge {#bridge}

Around 19hr we reached Kostrzyn. Here we were showed the route and we were told to cross the Oder before 20hr later we would not be allowed to. They blinked at us expressively. We concluded that they were well aware of our situation.

We did as we were advised. We almost reached the Odra. It was dark. On the Odra the traffic is tremendous. Full of troops. We did not stop for a moment. Over the Odra there was a footbridge of over a meter wide. Near the footbridge was a guard station. He did not stop us. After that, at the first foot-pillar of the bridge, there stood a second guard-house. In front of it there stood around fifteen guards, somewhat strangely dressed. They looked at us but no one interfered with us. We went the second foot-pillar of the bridge. There was a narrow kind of rails. We went through these rails to the tunnel and into the square where the signpost was. Darkness everywhere. Bolek put me on the signpost. I read: Stettin, Schwerin. We stood at a crossroad without knowing where to go. Bolek reminded himself of a German football team from Schwerin, who had played matches with Międzychód before the war. Apparently, it is a town located somewhere close to the border.

We headed towards Schwerin. We went into the woods. We wanted to get through it before the morning because we expected some German defences in the neighbourhood. On the way we read the signposts to the nearest towns - just in case. We did it within in a very short time. Maybe we already made 10 km, when we left the road, 300 m away, we noticed an illuminated building. Apparently some barracks. We entered the forest and unexpectedly we stood eye to eye with the soldier on guard. He was in charge of military warehouses. He shouted: "Halt!" A dog jumped out. He sniffed us and went back to the guardhouse. In a moment, without waiting for the guard to continue and before he knew, we were already next to him. "Why are you yelling?" I called and patted him on the shoulder. In case he would shoot, he would have had his piece, enough to cross to the other world. Apparently he noticed a German uniform because he hesitated. He lowered the rifle, which he had ready to fire. I told him we were going to the next village to buy something to eat. When we would come back, we would give him some. Without waiting for his consent, we set off in the designated direction.

On the way we met civilians on bicycles, who looked diligently at us. I looked at Bolek, he at me, but we did not see anything unusual that might draw their attention. After we lost sight of them, we went into the forest and all the way though the grove along the brook. Here in the thickets we sat down for a while and ... fell asleep. We must have slept for quite some time. We woke up from screams: "Deserters! Deserters! "I opened one eye. Over me stood a young German about twenty with a fusion prepared shooting me, and next to him a German women of about eighteen. They were watching us closely. I closed my eyes again, but immediately I jumped to him. He dropped the fusion, stepped back, and screamed out from the distance: "Deserters!", Threatening the gendarmerie. Near the hut was the there was a rattle. 

With one jump we were back into the forest and until evening we went and ran in unknown direction. In the evening we went out to the edge of the forest. We noticed two men covering a potato mound. Next to the mound stood a horse and an empty carriage. I went unnoticed under the mound. Having heard Polish talking, I went over. There were two of them. I greeted them in Polish. In the course of the conversation I learned that they are on the job. They promised to give us something to eat and even to sleep. I called Bolek, who at the time provided back-up. We got on the car and still during the light of the day we reached the village. They told us to wait. They were supposed to bring some cooked food. We couldn’t have waited; apparently they were too scared to help us out. After an hour, one of them came and ordered us to flee, because there is inspection. We did not have anything else but to actually march off.