# Hunger {#hunger}

We were so tired that we could not move much forward. We went a few miles, picked up potato leftovers in the field and like piglets stuffed them into us. So we hastened to dawn. It was terribly cold. We could not recognise each other in the morning. Dirty, tired, cold, we went further. The villages were still asleep. At times, there was a rooster's sound or dog barking. We happened to meet some soldier, but without a word we went on without asking him anything.

For us it was all the same now. We walked all day with small stops. We did not bypass the villages; Either we will come or we will die. We only eat carrots. On the way we found a corn field where we rested and ate a little. By evening we reached a village. Our march stopped by the trenches.

They were freshly dug, which intrigued us so much. Is there an Eastern Front already? We were afraid to go on. We landed in the roadside heap. Terrible cold and wind with rain did not give us any rest. We huddled together to warm ourselves up, but it did not help much.

Dawn. At a distance of 300 m from the heap stood a newly built large barrack. In the distance the village, and near the trenches stretched far away.

For long time no one was seen. Strangely calm. Terrible hunger began to sting us. There was no carrots or cabbage to be found in the vicinity. Around 10 o'clock it stopped raining. Underneath our pile came a boy and started to collect potatoes, which after the rain were easily visible. I went to him. I learned that Poles lived in the barrack, and for a period they were taken by Germans to dig trenches. Today is Sunday, so they do not work. He could not tell us where we were. At my request went to call a better-oriented colleague. Around 15:00 hour his colleague came. He also did not know much or did not want to tell us. He went out to find and bring a map for which we did not waited.

Night had fallen. The wind rose and it began to rain. What to do? We do not lose hope. If there are Poles in the camp, then some help will be given to us. I took off the uniform. Only in a sweater, without a hat, I went to the barrack. Bolek stayed for backup. I walked into the barrack. Party on the whole. Harmony plays from ear to ear. Nobody paid attention to me. I got to one of the elder men. It turned out he was from my region. He gave me bread and butter. The second portion I took for Bolek. After a long search, my friend came from under the heap. He dit not give me the map. He probably was afraid. I received a card from him to buy 2 kg of bread. None of the persons, however, could tell me exactly where we were. I went out. Bolek was already impatient.

We continued our journey. We walked along the railroad track. In the morning we came to a city. From the distance there were church towers. It was dark yet, and the ranks of people, with something like arms on their shoulders, were hurrying to the trenches. This made the impression of military manoeuvres, all the more when they started shooting with machine guns, and along the track was advancing an infantry. Under the light bulb we managed to escape to the pine grove. These were just military exercises.

It started to brighten up. Machine guns stopped firing. More and closer to us were the sounds of German commands. I reached out to the edge of the forest and saw straight in front of me the copse marching company of the army. Under the grove they stopped. They spread all the instruments for gun training. The soldiers divided into groups and started the training. Our location was tragic. Exiting into the open field would mean they will detect us. It could end up in a chase. Staying at the spot was also dangerous because during the break in the exercises the soldiers could enter the woods and would notice us. We stayed, however.

As we had predicted, there was a break in the exercises and several Germans entered the grove to help themselves with their physiological needs. We were unnoticed. To our joy, it began to rain. The company stopped the firing training and marched back.

There were more surprises that day. Suddenly Bolek got fever. He began to hallucinate. He complained that I was responsible for escaping, that we were in this situation and she wouldn’t move, that he would’ve live, and that he would have to die anyway, and so on. Under these conditions, marching further was no longer possible. I talked into him how I could, and when that did not work, we got edgy. Perhaps the weapon would break our dispute, but something like encouragement would come to us. It has been two weeks since this wandering in the dark. We looked into each other's eyes and kissed.

Bolek's fever did not go away, but he seemed to give himself completely to my care. He just asked not to leave him, and if so, notify his parents. I recalled the similar wishes of Józef Bartecki in Auschwitz, my best childhood friend. He is no longer alive. Did Bolek need to see this fate? This time, fate would be shared.

We shaved and cleaned as best as possible. Again the sun appeared in the west. Without waiting for the evening we set out for the city. On the way, comping back from the fields, a wooden wagon with ladies singing a Polish song. It seemed like good fortune.

We entered the city Meseritz (today Międzyrzecze) near Międzychodu. Bolek bought bread in the bakery that was waiting for us to disappear in our hungry stomachs. Next to the bakery stood a young boy with the letter "P". We started to chat with him and straightly explained to him how our situation. He promised to help us. He advised us not to go to the station, because there are constantly strict controls, especially from the military. He led us to colleagues who commute from Międzychod to work. He went ahead, and we followed him, twenty steps from behind. On the way we encountered a mass of soldiers in bright military hatbands. We gave each other the honors by raising our hands the Nazi way. So we fortunately crossed the whole city. In the northern part of the town was a sawmill owned by the Germans. There was a barrack in the backyard, and there in it lived the men to whom we were led by this unknown and honest Pole.

His colleagues were not there. They came in later in the evening. We made our We introduced ourselves to each other. They were very kind. Also Poles. They gave us warm coffee and bread. Warm coffee, we drank it for the first time since the escape. In return, as a hairdresser, I gave them all a haircut. I just finished cutting when the sirens were running. Air alarm. Mates all in fear. They just showed us the way and told us to run away because it could be control. So we did. We went along the railroad track towards Międzychodu. At the nearest station we had to get on a train that was leaving at 6am.

It was 26 October. The freezing did not allowed us to sleep. Our eye-lids were like glue. In the toilet at the station we waited until finally the train arrived. We paid for the ticket on the train. About 7 o'clock we arrived in Międzychodu. We gave the tickets at the exit of the station. We went to the estate 5 km away from Międzychodu. Bolek’s aunt was working there. It was already a bright day. Behind us were some uniformed men. Marching during the day was a risk.