---
output:
  pdf_document: default
  html_document: default
---
# Family {#family}

After an hour we reached the estate. We had to wait until the evening, so we hid in the woods just off the highway. One after an other, the hours passed by. We hoped that someone would take care of us. I did not know Bolek's aunt, but I've done everything I could to make myself happy, and most importantly, I'm going to sleep all night.

Somewhere nearby the children were playing, and from the distance came the singing of the soldiers and the words of the commander.

Finally, the long awaited evening came. At night I removed the uniform and the cap. Only in a military sweater and trousers, as a civilian, I went to the estate to look for Bolek’s aunt. Bolek did not know the exact address. He himself remained behind.

I did not have to look for long. The first local passerby I asked, pointed to the aunt’s apartment. I went to the room of a German woman. She pointed me to the next room. To reach the Aunt’s apartment I had to cross the german women’s room.

In the aunt's apartment I was received by her young cousin. The aunt was still at work. The cousin went out to look for her. Meanwhile, I was left home alone. I started from the kitchen, where potatoes were cooking. At the place I emptied half a pot - in split they disappeared in my stomach. I filled my stomach with bread and milk. I was almost fed up when aunt came in.

It was a little granny, wracked by work. She was about 55 years old. I asked if she knew Bolek Maciaszka. "Oh, Jesus, how do you know him? He's still alive ... Did he not die? "

I reassured her quickly. I told him he was alive and, unfortunately, he was here. As if lightning struck her... “Oh my sweet Jesus, where is he? ... What, you escaped from the camp? ..." I said yes. She just started to mourn ... "Give yourself up to the gendarmes ... give yourself up to the gendarmes. Maybe they will have some mercy ... Give yourself up the gendarmes, “ and on and on on she went. I did not let her finish because there was a German woman outside the door and she may hear something. I asked firmly whether she wanted to see Bolek or not. She nodded, and she did not mention the gendarmerie. I told her to take something to eat and follow me.

She recognised Bolek at once. She began to lament again as before. "There are so many soldiers here, gendarmes. They'll shoot you ... they'll shoot. You will not get out of here. You better give yourself up the gendarmes. "

Bolek shut her up and said that she should stop saying rubbish. He took bread and coffee, fed himself a little and said goodbye to his aunt, and half-confidence we moved ahead, without direction. Just not stay stay on one place. We were heading north. We reached Zatom station. Bolek recalled this mate Spychał from the Neuengamme camp at the Messap Commander. Somewhere near Zatom his brother lived. We sat in the hall until 4:00, and then went down the path towards the village. Bolek went ahead, and I was lagging behind in thoughts about our fate. To join the partizans… But how to contact them? I was about thirty steps behind when I heard: "Halt! Wohin gehen Sie? "Bolek replied something. The tall man staggered out of the darkness. He went to Bolek at the same time as I came. He saw our SS military uniforms, he began to talk politely. We said we were going to the front. We wanted to see Spychał. The man - as it turned out - returned from the night watch, walked on, and we went to Spychał. We went down to the courtyard; It was still dark. In the barn the woman dug the cows, and Spychał "turned" the horses. After a moment he came to us, we sat on a bench near the window of the house. We began to question him about the brother from the camp, until suddenly from all the sides came shouts: "Halt! Hände hoch! " In front of the group was the same German who met us on the road. He demanded documents and that we went with him to the gendarmerie. "You do not speak German very well - it is suspicious."