# Fiancee {#fiancee}

I did not hesitate. I jumped at this German and screamed with camp-language as hard as I could, using the words I learned from the captain in the worst moments of my life in the camp. "What! A soldier of the Third Reich is supposed to identify himself to civilians? Have you become complete idiots? You lay around like pigs, and we shed blood for you at the front! And now you and you dare to bother us? An SS soldier never had to identify to anyone. I will write on you to the Fuhrer himself. We will hang you like stray dogs! Heil Hitler! "

They immediately lowered their weapons that they had pointed at us and responded: "Heil Hitler."

We did not wait very long. Without a word, we left the village boundaries, into the fields and meadows, and then through the ditches to the forest. I do not know if Kusociński would be able to catch up with us at that moment, We jumped over deep ditches, of which at other times we would not dare to cross.

We often remember those moments with Bolek and Spychała, who later interrogated for a few weeks. Spychał did not know us at all. So he could not say much about us, so he was no longer persecuted.

We were in the woods for a long time. Often on the path we meet civilians riding on bicycles. They did not bother us.

We went down the hill next to Ryżyn. Last helpdesk, Bolek's fiancée. Apparently living in Ryżyn. From there she sent packages to the camp. At dusk we went to the village. It was hard to recognise anything. Many buildings and barns were demolished. This is Bolek's family place. Here he was born and raised. Unfortunately, he could not orientate himself well.

PAGE 17
This time I stayed put, and Bolek went to the fiancée’s house. In a moment he is running back with frightening cries: "Run away!" We ran through the footbridge on the creek. We disappeared in the dark. What happened? He entered a house where, instead of finding a fiancée, he found “Wołyniak" (fighters?).

We peered through fences and windows to the buildings to meet at least one familiar face. Unfortunately, we encountered only unknown faces. Displaced Poles...

The last cottage of the village side, opposite the station to which we directed our steps, lived the father of the bride. Through the window Bolek recognised the faces of the Czes family. It was already late in the evening. An explosion of joy. One jump and Bolek rushed into the apartment. In a moment an older man went in that passed me without noticing me. After a few minutes, I too was called in.

We were in a Polish family. The door was closed, the windows shut and the dinner started. Our story would’ve been un-ended if not for the fact that we were wasted...

We slept without a break for two days and two nights. I did not hear how I was woken. I ate in a sleep, because I can not remember anything. On the evening of the third day, I dressed in Bolek's uniform again, because mine was worn to the seam and my shoes fell apart on the road. From this moment on I was wearing: striped camp underwear, striped clothes with a number and red triangular, and Bolek’s uniform. At last I was warm. The witnesses: Bolek, fiancé and father-in-law said that I look like a real SS-er.

Bolek got civilian clothes from his father-in-law. He took the pistol, and me the case. I was satisfied with this. As a payment for the dividing I received 10 marks, for which I bought a ticket at the station Ryżyn to Wieluń. Bolek escorted me to the station. Here we said goodbye. From here each of us had carers, and I ...