# Stations {#stations}

Finally, the train arrived in the direction of Szamotuł. I was traveling alone. Without arms. I could only save myself by escape.

In Szamotuł I did not got out on the station. On the platform I was waiting for the train coming from Szczecin to Poznan. After an hour's delay, the train approached. Luckily I got to Poznan. In Poznan I had to got off. The train was not going any further. So easy to say: “got off”. At the station it was full with gendarmes with metals. At any moment they could hold me and identify me. What would be the end of that - it is easy to predict.

At the exit towards the city, everyone was legitimated, and the military police escorts were on the side. To make matters worse, the train heading for Ostrów Wielkopolski had already departed, as my train had a delay of half an hour. The next train would be at 6:00, after 10 hours. Throughout our escape we avoided large stations, and here at this moment I was alone, accidentally, in the middle of danger. What to do?

I went down to the tunnel. Many people waited for the train. I read all announcements, timetables I did not had a clue about. The gendarmerie was constantly walking around. Only the metals on their chests were buzzing. I did not look into their direction at all. The metals announced they were close to me. I do not know why I was not ask for identification. Apparently they were scared of the skulls on the cap and collar. Or maybe I looked so fierce that I did not raised any suspicions.

An army transport arrived. I mingled up with them, and after their departure, I spent the rest of the night ready for surprises. Apparently I was thought not to die just yet. Nobody stopped me.

At 6:00, I got on the train departing towards Ostrów Wielkopolski. The stone fell from my heart. A soldier came to sit next to me. He asked something about something. I pretended I was napping. I was happy to get out of the worst of the worst. There was only one ticket control on the Poznan-Ostrów Wielkopolski route. I remembered the time three years ago. I put on travel, driven by the Gestapo. Here I heard lamentations of mothers, wives and children who were walking their loved ones to death. From here we drove to the concentration camp in Auschwitz ...

After a few minutes of stopping, we continued in the direction of Kępno. More people were filling up the wagon. There was a German woman about thirty years old. She started to hook up to and ask me about things, and when I did not answer her, she called me tightwad. What was I supposed to do? I accepted this silence. Finally she calmed down.

At 9 o'clock we entered the Kępno station. Here I had to change to a train going in the direction of Wieluń. What I saw after leaving the train terrified me. The whole train surrounded by the gendarmes. Everyone was told to show documents at the exit. Special inspection.

It was a bright sunny day. An escape could was unthinkable. The first effects of the control could quickly be seen. They beat the face of one, kich another, others take to the side. Judgement Day. Not many people got up easily from the upper platform to the station. I was in the middle. I walked along the train, but they were also checked. I waited for what was going to happen next. I became the last in the queue. I took a cover from a notebook that accidentally found in my pocket. I put the ticket on the cover. I was slowly moving all the way forward. The inspection lasted for an hour. The end was near - my turn was approaching. A granny had something in her backpack; was beaten up and taken to the side.

I approached and did not stop. Ticket on the cover of the notebook in the left hand, I saluted right and said: "Heil Hitler." He answered "Heil Hitler" and ... I went on.

I went to the station. Everything in me shaking. Sweat appeared on the forehead. There was a whistle, and the whole mass of the gendarmes moved to the front. There was a whistle and the masses of gendarmes were getting on at the station. They took the whole waiting room class 1 and 2. They had no place. The late-comers were walking in the corridor, glancing at me from time to time.



I bought a newspaper "Völkischer Beobachter". I read, or rather pretended to read, from beginning to end. Time was passing awry. Around 11 o'clock the train arrived. The first to get were the gendarmes. I slipped forward one wagon further. So I got to Wieluń at about 12 o'clock. Before the train even came to a halt, I jumped off. I gave the ticket to the station master. I was hiding in the closet because another hiding place was not availale. The gendarmes drove on, supposedly for the pacification of the forests.

In the evening I left my hiding place. Slowly I went to the city, 3 km from the station. I did not know the Wielun. I was in prison for three years before I was taken to Auschwitz. I only knew that the Kwieciń family live at the Landbergerstrasse and have a butcher shop and that Lewandowska family, the seamstress, lives at Gaschinerstrasse 5. Other people in this town I did not know. There was no fear that anyone would recognise me either.

##### NOTE from translator
_Wielun station was a kind of collection and transportation hub. People from different corners were sent by the Nazi's to Wielun and subsequently transported to their final destinations. In 1942/43, my grandfather (Bolek Jabłoński), grandmother (Józefa Jabłońska, sister of Stanisław Czernicki, and pregnant from my mother) and two of their sons, were taken prisoner from Brzeznica and transported to Wielun. From there, they were sent to Doncourt-Cités (France) work camp._ 
