# Hiding {#hiding}

And finally the city. Every now and then, some young Germans greeted me: "Heil Hitler." I had to respond with similar greetings. I seemed to me that there were may Germans here. I arrived at Landsczy. I did not know Mrs. Kwiecinska, who was selling meat in the store. I went on to Gaschinerstrasse. It was an isolated small wooden house. I did not go, but I waited until it got dark. I walked along the street. As I learned later, it was a district of the Gestapo.

Finally I decided to enter. Without knocking and without removing the cap I found myself in the apartment. There was an old lady in the kitchen. Five dressmaker's aids were sewing at the center table. One of them I knew. She was the one who brought me food in the jail. She did not recognise me.

I asked in German whether Mrs. Lewandowska lives here. I was affirmed and was sent to the other room. I was happy because I did not want to meet my girlfriend.

In the second room there was a measuring of fur for two grimy German women. I waited for quiet long enough for them to finish the measuring. The Germans were chattering. In the end I could not stand it anymore. The curfew was approaching. I called the Germans to hurry, because I still have something to do here, and the hour is late. They wanted to pass me as first, but I resolutely refused. They froze. They slammed the door and left.

Mrs. Lewandowska wanted to call "dolmeczerkę" - a translator. I answered in Polish. I introduced myself of who I am. She did not believe me. She did not know recognised me at all. I took off my cap. She sat down with amazement. She could not take me in for overnight. Quickly, before the curfew, she escorted me to the Kwieciński family. They accepted me in the other room, so that no one would notice. They did not know me. Daughters came from the city and they also did not know me. Just in case, I was told to take off my military uniform. For the time being they gave me civilian pants. After dinner I was given a room with an Armanean apprentice.

A human gets used to everything. I got used to the cold air. I could not sleep now in a hot room. The whole night was like having a fever. I could not sleep. At dawn I asked for some other place to sleep. Stefan led me over the stable in the yard. It was full of hay. I was very nice. Through the cracks at the top of the stables I got acquainted with the location of the neighbouring buildings. It was 1 November 1944.

On the second of November, at 9 o'clock Stefan entered the stable and shouted, "Gestapo!" He disappeared. I looked through the cracks. The courtyard was full with Gestapo. They were all armed, they turned the house up-side down. Well, this time - I thought - I will not squeeze myself out of trouble. Someone must have betrayed. Escape is impossible. For a long time the Gestapo guys were discussing something in the yard. Through the cracks I could not see anything. Eventually the group left the house. Mister and Misses Kwieciński were taken to the car. They drove off. There was silence. I was saved again.

An hour later, Kwieciński's daughter, Henia, arrived. She took me to Kieszkowski. Later Kieszowski told me that Henia was also arrested after having brought me to safety.

I was placed in the attic over the barn. There were strong winds blowing through. In the evening, Kieszkowski led me to the basement. Here I sat until November 7, until I was released by the older daughter Genia Kwiecińska. There was a document for a foreigner named Stanisław Starzał, and by the veterinary doctor Fronczak I was sent to work in Borsigwerk near Bytom. At an appointed signal, I went on the Wieluń - Częstochowa highway. Here a man came riding a motorcycle, supposedly a German, and took me to the next station behind Wielun, Pątnów. I was checked at the station in Wieluń. Pakosia, the fiancee of Kwieciński’s son, took me to the family of Dr. Fronczak. But we did not find the doctor; I was forced to travel alone to my future job.

Later, I was told what the Kwieciński arrest was about. Stasiek, the son of Kwiecinski, passed through the policeman's field with his fiancé Pakosia. The gendarme came. A quarrel broke out at which Stasiek hit the gendarme. Stasiek escaped to Kraków and hid there until the end of the war. The Gendarme appealed to the Gestapo of Wieluń, and when nothing came out of the Kwiecinski case, they wrote to the Gestapo in Łódz. It was then that the Gestapo from Łódz arrived and arrested the Kwieciński family. They were released after some time. They were looking for a son from Kwieciński, and by chance, almost found me ...