# Work {#work}

I arrived at the place of my future work safely. I applied to Kleinert. I handed to him the papers. I was accepted for work. It involved wearing and laying rail rails at the Borsigwerk station. I stayed in the barrack. There were about forty of us. The food, as in the camps, tasted great. I received a certificate as a railway worker. After work I was able to move freely. I went to Bytom. I wrote letters to the concentration camp in Neuengamme, to Zdzich Piwowarczyk from Radomsko and to his fiancée Kazi Wrzalikówny in Radomsko. I did put the return the address on the envelope.

Meanwhile, in my hometown, Brzeźnica nad Warta, on the border of the Reich with the General Government, they were notified about our escape. The gendarmerie called for help of the border guards and they were constantly looking for me. Vigilance on the border was reassigned. To my father's house, they did the most accurate revisions, including the removal of floors. In the presence of Morga, a resident of Brzeźnica, who served as an interpreter, houses were thoroughly inspected every few days for all the attics and cellars, and finally my parents were arrested.

It is unknown what would have happened if the sad accident hadn’t determined their fate. Well, two fugitives, apparently in a similar situation to ours, drove the freight train. Before the station in Brzeźnica, serving as a borderline, they jumped out of the train. They had apparently noticed them, because all the border guards and gendarmes were on their feet and the border was crawling with guards.

The result was sad. The poor, unknown refugees did not expect anything. At dusk they came out of the hideout to cross the border. They went straight into the checkpoints. They received a series of machine guns. They died on the spot.

My parents were taken out of prison to identify the bodies. It was already dark, as my father told me. In the light of the electric lights, the facial features seemed similar. According to the data one was bigger and the other, like me, smaller. Dirty from the mud, it was not easy to recognize.

At the sight of the dead, the parents fell into despair and recognized in one of the lying corpses as being me.

To the great joy of the Germans, and the despair of the parents, a photograph was taken which was then sent to the concentration camp in Neuengamme. The parents were released from prison and the dead were send to the morgue.

As this, I was deleted from the German records of the living. After returning home and mourning my death, the parents began to think about the whole incident. At one point they recalled that I was wounded in the left leg and arm during the war in 1939. I had a scar on my left leg and on my left hand. The mother decided to go to the corpse and identify the corpse of the dead. None of the corpses found scars. She was very happy. She returned home, not telling anyone about it, except my father.

The work in Borsigwerk was quite heavy. It would not be unusual for my work if it were not for the fact that I had to provide my place of birth and the last place of residence, which was Krumbach (Wielkopolska) under the Wieluń. From where many of my current colleagues came from. They started asking me where I lived, where I worked, etc. I was like a snake trying to crawl out of it. I could not get out of this, and little suspicion could decide my life. I did not even see this place, even didn’t knew about it. Starzała, whose name I received, was certainly born there and lived there, but I did not even know where this Krzyworzeka place was.

During the winter we drove snow from the Borsigwerk and Bobrek railway tracks. That's how November and December passed by. For Christmas, I went to Wieluń to visit the Kwieciński. On the road there were tight controls on the trains. Many of my current colleagues are arrested. I returned safely I went back to wait for the liberation.

In Borsigwerk and the surrounding area, the controls were tightened. Documents were checked at every opportunity, even at the exit of the cinema. Our barracks were visited by the Gestapo more and more often. From time to time, colleagues were taken away at night.

I was constantly on the alert. I took charge of the snow at night, and in the day I slept a little, so as not to fall into the hands of the Gestapo.

Upon returning from Wielun, they began to check me out. My personal data was written the second time. More and more they got interested in me. I had to disappear. I managed to get Biskupic. There I got a job at a bakery at Czernego (supposedly a Czech German). I replaced the baker who had gone to the army. In the bakery, working as a "professional" baking rolls of bread I survived until the entry of Soviet troops.